apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-admin
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
