apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-get-watch-ls-binging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-watch-ls
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
