apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: mysqls.otus.homework
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: otus.homework
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: MySQLSpec defines the desired state of MySQL
              properties:
                # свойства спецификации кластера (.spec)
                image:
                  description: image for MySQL
                  type: string
                database:
                  description: MySQL database name
                  type: string
                password:
                  description: MySQL admin password
                  type: string
                storage_size:
                  description: MySQL storage size
                  type: string
              required:
              - image
              - database
              - password
              - storage_size
              type: object
            # назначение ключа объекта yaml .status (пустой объект)
            status:
              description: MySQLStatus defines the observed state of MySQL
              type: object
          type: object
  # either Namespaced or Cluster
  scope: Namespaced
  names:                # различные форматы имени объекта CR
    kind: MySQL         # kind CR
    plural: mysqls
    singular: mysql
    shortNames:
      - ms
