apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
   containers:
     - name: nginx
       image: darudcha/nginx:latest
       volumeMounts:
         - name: app
           mountPath: /app
       ports:
         - containerPort: 8000
   initContainers:
     - name: init
       image: busybox:1.35.0
       command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
       volumeMounts:
         - name: app
           mountPath: /app
   volumes:
     - name: app
       emptyDir: {}
