apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
   containers:
   - name: nginx-web-pod
     image: darudcha/web-pod:v0.0.3
     readinessProbe: # Добавим проверку готовности
       httpGet: # веб-сервера отдавать
          path: /index.html # контент
          port: 80
     volumeMounts:
     - name: app
       mountPath: /usr/share/nginx/html
     ports:
     - containerPort: 8000
   initContainers:
   - name: index
     image: busybox:1.35.0
#     command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
     command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
     volumeMounts:
     - name: app
       mountPath: /app
   volumes:
     - name: app
       emptyDir: {}
